#!/bin/sh

# Get the path of the script
cd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
cd - > /dev/null
echo $SCRIPTPATH

RAP_ADDR='10.16.3.1' RACKATTACK_PROVIDER_URI="${RAP_ADDR}" RACKATTACK_PROVIDER=tcp://${RACKATTACK_PROVIDER_URI}:1014@@amqp://${RACKATTACK_PROVIDER_URI}:1013/%2F@@:${RACKATTACK_PROVIDER_URI}:1016 UPSETO_JOIN_PYTHON_NAMESPACES=yes PYTHONPATH=$SCRIPTPATH/../py python $SCRIPTPATH/print_hosts_stats.py
